version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk
      
    steps:
      - checkout

      - run:
          name: Build solution
          command: dotnet build